ADCIO-1644) feat: add analytics log function
corca-ai/adcio_demo_app_ios pull request #4
Opened 2023-11-15 07:37 UTC by aahspringaa4

ADCIO Plugin Analytics를 Demo앱에 붙혔습니다.

https://github.com/corca-ai/adcio_demo_app_ios/assets/77616769/d0e03b11-38ba-43aa-a38c-e992d5a783d1

2023-11-15 07:41 UTC, adbr-dev requested changes
윗부분만 봤는데 수정 코멘트가 나왔네요 다시 꼼꼼히 보고 수정 부탁드려요

2023-11-15 07:41 UTC, adbr-dev commented on adcio_demo_app_ios/Data/FetchProductData.swift
흠.. 이거 파일 수정은 analytics 붙히는 feature에 들어가는게 아닐 것 같은데..

2023-11-15 07:41 UTC, adbr-dev commented on adcio_demo_app_ios/Screen/Chart/ChartView.swift
>              Text("Chart")
chart..? 차트..? cart..?를 나타내고 싶었던걸까요?

2023-11-15 07:41 UTC, adbr-dev commented on adcio_demo_app_ios/Screen/Chart/ChartView.swift
> +                path: "ProductDetail",
path도 잘못되어있어요

2023-11-15 07:46 UTC, aahspringaa4 commented on adcio_demo_app_ios/Screen/Chart/ChartView.swift
> +                path: "ProductDetail",
앗.. 수정했습니다

2023-11-15 07:46 UTC, aahspringaa4 commented on adcio_demo_app_ios/Screen/Chart/ChartView.swift
>              Text("Chart")
해당 네비게이션 이름이 '목록'이라 chart라는 이름을 계속 사용하고 있었습니다.

2023-11-15 07:48 UTC, aahspringaa4 commented on adcio_demo_app_ios/Data/FetchProductData.swift
아하.. click에서 logOption 사용을 위해 값 받아오는 부분을 일부 수정했습니다.

2023-11-16 08:09 UTC, adbr-dev requested changes

2023-11-16 08:09 UTC, adbr-dev commented on adcio_demo_app_ios/Screen/Chart/ChartView.swift
>              Text("Chart")
잉? 무슨 말이예요? 네비게이션이랑 페이지 우리가 임시로 만드는거아녜요?? 그리고 목록을 chart 라고 명명하신거예용..?

2023-11-16 08:09 UTC, adbr-dev commented on adcio_demo_app_ios/Data/FetchProductData.swift
> +        suggestion(productValue)
저 진짜 죄송한데 suggestion(productValue)값 넘기는 이유가 뭐예요..?
이거 analytics 코드 수정.. 아니였나요? option값은 넘겨서 사용한다 하지만 저 값은 무엇..인지 이 feature에 무슨 연관이 있는지 설명해주실 수 있나요 ?

2023-11-16 08:15 UTC, aahspringaa4 commented on adcio_demo_app_ios/Screen/Chart/ChartView.swift
>              Text("Chart")
` 네비게이션이랑 페이지 우리가 임시로 만드는거아녜요??`
맞아요..! 근데 page가 넘거가긴 해서 onPageView 달아놓았습니다! 굳이 필요하지 않다면 제거해도 될 것 같아요!

`목록을 chart 라고 명명하신거예용..?`
녜.. 목록하고 chart는 거리가 있는 말이려나요..?

2023-11-16 08:16 UTC, aahspringaa4 commented on adcio_demo_app_ios/Data/FetchProductData.swift
> +        suggestion(productValue)
analytics에 performance (click & impression)을 위해서 logOption 값이 필요한데, 이는 placement에서 받아와서 처음에 placement 호출 할 때 같이 받아온뒤 저장해 두었다가 analytics click에서 사용하고 있습니다.

2023-11-16 08:18 UTC, aahspringaa4 commented on adcio_demo_app_ios/Data/FetchProductData.swift
> +        suggestion(productValue)
원래는 [ProductEntity]만 리턴으로 반환하고 있었는데 사용부에서 한번의 두개 이상의 Entity 를 받게 되니 매개변수의 클로져로 받도록 저런식으로 구현하였습니다.

2023-11-16 08:19 UTC, aahspringaa4 commented on adcio_demo_app_ios/Data/FetchProductData.swift
> +        suggestion(productValue)
suggestion은 GridView에 사용되고 logOption은 analytics에서 사용됩니다!

2023-11-16 08:32 UTC, adbr-dev commented on adcio_demo_app_ios/Screen/Chart/ChartView.swift
>              Text("Chart")
넹.. chart.. 차트 .. 밖에 생각 안나요 **이건 나중에 feature 브랜치 나눠서 수정하면 좋을 것 같아요** 
단순 네이밍만 바뀌는거니깐 PR은 따로 필요없을 것 같고 local 내에서 feature 만들고 finish 해서 develop에 올려주시면 좋을 것 같아요

2023-11-21 04:55 UTC, adbr-dev approved these changes

2023-11-21 04:55 UTC, adbr-dev commented on adcio_demo_app_ios/Screen/Chart/ChartView.swift
> +        .onAppear{
onPageView 선언: 최초 페이지 init + **button 앞전** 
build 될때마다 안되었으면 함

2023-11-21 05:01 UTC, merged